name: plugin-continuous-delivery
concurrency: delivery-pipeline

on:
  push:
    branches: ["master"]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build

      - name: Publish
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: publishPlugins
